services:
  postgres:
    image: postgres:16.3
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  rails:
    build:
      context: .
      args:
        RAILS_ENV: development
        BUNDLE_WITHOUT:
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: niu_foods_app
    depends_on:
      - postgres
      - sidekiq
    env_file:
      - .env
    image: gabo_71096/niu_foods_app:1.0
    ports:
      - 3000:3000
    volumes:
      - .:/rails
    restart: always
  redis:
    image: redis:7.2.5
    restart: always
    command: redis-server
  sidekiq:
    build:
      context: .
      args:
        RAILS_ENV: development
        BUNDLE_WITHOUT:
    command: bundle exec sidekiq -C config/sidekiq.yml
    container_name: niu_foods_background_jobs
    depends_on:
      - redis
    env_file:
      - .env
    image: gabo_71096/niu_foods_app:1.0
    restart: always
    volumes:
      - .:/rails
